name: smart_account_sms
description: Arabic customer balance messaging app for Smart Account / Daftar Al Hesabat.
publish_to: 'none'
version: 0.5.5+10

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/index.html
